ArquitecturaWeb/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('lirApp/', include('lirApp.urls')),
    path('admin/', admin.site.urls),
]

lirApp/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('agregar_cliente', views.agregarCliente, name='agregarCliente'),
    path('clientes', views.ListaClientes.as_view(), name='listaClientes'),
    path('clientesAprobados', views.ListaClientesAprobados.as_view(), name='ClientesAprobados'),
    path('clientesRechazados', views.ListaClientesRechazados.as_view(), name='ClientesRechazados'),
    path('clientes/(?P<pk>\d+)$', views.ClienteDetalle, name='clienteDetalle'),
    path('clientes/aprobar/(?P<pk>\d+)$', views.ClienteAprobar, name='clienteAprobar'),
    path('clientes/rechazar/(?P<pk>\d+)$', views.ClienteRechazar, name='clienteRechazar'),
]

lirApp/models.py
from django.db import models

# Create your models here.
class Cliente(models.Model):
    TIPO_PROCEDIMIENTO = (
        ('LP', 'Liquidación Persona'),
        ('LE', 'Liquidación Empresa'),
        ('RP', 'Renegociación Persona'),
        ('RE', 'Reorganización Empresa'),
    )
    ESTADO = (
        (1, 'PENDIENTE'),
        (2, 'APROBADO'),
        (0, 'RECHAZADO'),
    )
    rut = models.CharField(max_length=25)
    nombre = models.CharField(max_length=255)
    apellidos = models.CharField(max_length=255)
    id_crm  = models.IntegerField(default=0, null=True, blank=True)
    tipo_procedimiento = models.CharField(max_length=2, choices=TIPO_PROCEDIMIENTO)
    estado  = models.IntegerField(default=1, choices=ESTADO)
    def __str__(self):
        return '%s %s %s' % (self.rut, self.nombre, self.tipo_procedimiento)

class Acreedor(models.Model):
    TIPO_ACREEDOR = (
        ('1', 'Banco de Chile'),
        ('2', 'Otros bancos'),
        ('3', 'Cajas'),
        ('4', 'Retail'),
        ('5', 'Otros'),
    )
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=255)
    tipo_acreedor = models.CharField(max_length=1, choices=TIPO_ACREEDOR)
    monto = models.IntegerField()
    moneda = models.CharField(max_length=1)
    def __str__(self):
        return '%s %s %s' % (self.cliente, self.nombre, self.tipo_acreedor)

lirApp/forms.py
from django import forms

from .models import Cliente

class ClienteForm(forms.ModelForm):

    class Meta:
        model = Cliente
        fields = ('rut', 'nombre','apellidos','tipo_procedimiento',)

lirApp/views.py
from django.shortcuts import render
from django.views import generic
from .forms import ClienteForm
from .models import Cliente
from django.shortcuts import redirect
from django.http import HttpResponse
from django.http import Http404
from django.shortcuts import get_object_or_404

# Create your views here.


def index(request):
    return HttpResponse("<a href='http://dramz.pythonanywhere.com/lirApp/clientes'>listado de clientes<a/><a href='http://dramz.pythonanywhere.com/lirApp/agregar_cliente'>Agregar Cliente<a/>")

#def agregarCliente(request):
#    return HttpResponse("You're looking at question.")

#def agregarCliente(request):
#    form = ClienteForm()
#    return render(request, 'agregar_cliente.html', {'form': form})

def agregarCliente(request):
    if request.method == "POST":
        form = ClienteForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            #post.author = request.user
           # post.published_date = timezone.now()
            post.save()
            return redirect('listaClientes')
    else:
        form = ClienteForm()
    return render(request, 'agregar_cliente.html', {'form': form})

class ListaClientes(generic.ListView):
    model = Cliente
    context_object_name = 'lista_clientes'
    queryset = Cliente.objects.filter(estado=1)
    template_name = 'lista_clientes.html'


class ListaClientesAprobados(generic.ListView):
    model = Cliente
    context_object_name = 'lista_clientes'
    queryset = Cliente.objects.filter(estado=2 )
    template_name = 'lista_clientes_aprobados.html'

class ListaClientesRechazados(generic.ListView):
    model = Cliente
    context_object_name = 'lista_clientes'
    queryset = Cliente.objects.filter(estado=0 )
    template_name = 'lista_clientes_rechazados.html'

def ClienteDetalle(request,pk):
    try:
        cliente_id=Cliente.objects.get(pk=pk)
    except Cliente.DoesNotExist:
        raise Http404("Book does not exist")

    #book_id=get_object_or_404(Book, pk=pk)

    return render(
        request,
        'cliente_detalle.html',
        context={'cliente':cliente_id,}
    )
def ClienteAprobar(request,pk):
    try:
        cliente_id=Cliente.objects.get(pk=pk)
    except Cliente.DoesNotExist:
        raise Http404("Book does not exist")

    cliente_id=get_object_or_404(Cliente, pk=pk)
    #obj.name = "some_new_value"
    cliente_id.estado = 2

    cliente_id.save()
    return redirect('ClientesAprobados')
    #return render(
       # request,
        #'cliente_detalle.html',
        #context={'cliente':cliente_id,}
    #)
def ClienteRechazar(request,pk):
    try:
        cliente_id=Cliente.objects.get(pk=pk)
    except Cliente.DoesNotExist:
        raise Http404("Book does not exist")

    cliente_id=get_object_or_404(Cliente, pk=pk)
    #obj.name = "some_new_value"
    cliente_id.estado = 0

    cliente_id.save()
    return redirect('ClientesRechazados')

lirApp/templates/agregar_cliente.html
{% extends "base.html" %}
{% block content %}
    <h2>Nuevo Cliente</h2>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Guardar</button>
    </form>

{% endblock %}

lirApp/templates/base.html
{% load static %}
<html>
    <head>
        <title>Proyecto Arquitectura Web</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    </head>
    <body>
        <div class="content container"
            <nav class="navbar navbar-inverse bg-primary" role="navigation" >
                  <div class="navbar-header">
                    <a class="navbar-brand"  href="http://dramz.pythonanywhere.com/lirApp/clientes">Sistema LIR</a>
                  </div>
                    <ul class="nav navbar-nav navbar-right">

                      <li class="dropdown">
                        <a href="#"  class="dropdown-toggle" data-toggle="dropdown">
                          Bandejas <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                          <li><a href="http://dramz.pythonanywhere.com/lirApp/clientes">Por probar</a></li>
                          <li><a href="http://dramz.pythonanywhere.com/lirApp/clientesAprobados">Aprobados</a></li>
                          <li class="divider"></li>
                          <li><a href="http://dramz.pythonanywhere.com/lirApp/clientesRechazados">Rechazados</a></li>
                        </ul>
                      </li>
                    </ul>

            </nav>
        </div>

        <div class="content container">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

lirApp/templates/cliente_detalle.html
{% extends "base.html" %}
{% block content %}
  <h2>RUT: {{ cliente.rut }}</h2>

  <p><strong>Nombre:</strong> {{ cliente.nombre }}</p>
  <p><strong>Apellidos:</strong> {{ cliente.apellidos }}</p>
  <p><strong>Tipo Procedimiento:</strong> {{ cliente.tipo_procedimiento }}</p>
  <p><strong>Estado:</strong> {{ cliente.estado }}</p>
  <p><strong>CRM ID:</strong> {{ cliente.id_crm }}</p>
  <a class="btn btn-success" href="{% url 'clienteAprobar' cliente.pk %}">Aprobar<a/>
  <a class="btn btn-danger" href="{% url 'clienteRechazar' cliente.pk %}">Rechazar<a/>
{% endblock %}

lirApp/templates/lista_clientes.html
{% extends "base.html" %}
{% block content %}
    <h2>Lista Clientes por Aprobar</h2>

    {% if lista_clientes %}

    <table class="table">
      <thead>
        <tr>
          <th scope="col">RUT</th>
          <th scope="col">Nombre</th>
          <th scope="col">Apellidos</th>
          <th scope="col">Tipo Procedimiento</th>
          <th scope="col">Estado</th>
        </tr>
      </thead>
      <tbody>
          {% for cliente in lista_clientes %}
          <tr>
              <th scope="row"><a href="{% url 'clienteDetalle' cliente.pk %}">{{cliente.rut}}</a></th>
              <td>{{ cliente.nombre }}</td>
              <td>{{ cliente.apellidos }}</td>
              <td>{{ cliente.get_tipo_procedimiento_display }}</td>
              <td>{{ cliente.get_estado_display }}</td>
            </tr>
          {% endfor %}
      </tbody>
    </table>
    {% else %}
      <p>No hay clientes a mostrar.</p>
    {% endif %}

    <a class="btn btn-success" href='http://dramz.pythonanywhere.com/lirApp/agregar_cliente'>Agregar Cliente<a/>
{% endblock %}

lirApp/templates/lista_clientes_aprobados.html
{% extends "base.html" %}
{% block content %}
    <h2>Lista Clientes Aprobados</h2>

    {% if lista_clientes %}
    <table class="table">
      <thead>
        <tr>
          <th scope="col">RUT</th>
          <th scope="col">Nombre</th>
          <th scope="col">Apellidos</th>
          <th scope="col">Tipo Procedimiento</th>
          <th scope="col">Estado</th>
        </tr>
      </thead>
      <tbody>
          {% for cliente in lista_clientes %}
          <tr>
              <th scope="row"><a href="{% url 'clienteDetalle' cliente.pk %}">{{cliente.rut}}</a></th>
              <td>{{ cliente.nombre }}</td>
              <td>{{ cliente.apellidos }}</td>
              <td>{{ cliente.get_tipo_procedimiento_display }}</td>
              <td>{{ cliente.get_estado_display }}</td>
            </tr>
          {% endfor %}
      </tbody>
    </table>
    {% else %}
      <p>No hay clientes a mostrar.</p>
    {% endif %}

{% endblock %}

lirApp/templates/lista_clientes_rechazados.html
{% extends "base.html" %}
{% block content %}
    <h2>Lista Clientes Rechazados</h2>

    {% if lista_clientes %}
    <table class="table">
      <thead>
        <tr>
          <th scope="col">RUT</th>
          <th scope="col">Nombre</th>
          <th scope="col">Apellidos</th>
          <th scope="col">Tipo Procedimiento</th>
          <th scope="col">Estado</th>
        </tr>
      </thead>
      <tbody>
          {% for cliente in lista_clientes %}
          <tr>
              <th scope="row"><a href="{% url 'clienteDetalle' cliente.pk %}">{{cliente.rut}}</a></th>
              <td>{{ cliente.nombre }}</td>
              <td>{{ cliente.apellidos }}</td>
              <td>{{ cliente.get_tipo_procedimiento_display }}</td>
              <td>{{ cliente.get_estado_display }}</td>
            </tr>
          {% endfor %}
      </tbody>
    </table>
    {% else %}
      <p>No hay clientes a mostrar.</p>
    {% endif %}

{% endblock %}